name: Build and deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: npm install --legacy-peer-deps
        working-directory: KotibotWeb/ClientApp
      - run: dotnet build --configuration Release
      - run: dotnet publish --configuration Release -o ./KotibotRelease
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'kotibot'
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          package: ./KotibotRelease
      